# 1 https://pastebin.com/vdQgBExm
# 2 https://pastebin.com/qrFfWAcY
# 3 https://pastebin.com/0BZnCXJn
# 4 https://pastebin.com/zxUMz7kD
# 5 https://pastebin.com/mWs7NTD2
# 6 https://pastebin.com/Z1mvcvGg
# 7 https://pastebin.com/dTg5kBch
# 8 https://pastebin.com/9PyVaNqv
# 10 https://pastebin.com/8NiRiqcx